-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')
--Added plugin that add corect highlighting
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.neotree')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.buffline")
require("plugins.comments")
require("plugins.lualine")
require("plugins.outline")
require("plugins.toggleterm")
